---
# playbook.yml
- name: 'Jiangren Packer demo2'
  hosts: default
  become: yes
  become_user: root
  user: ubuntu

  file:
    path: /var/lib/apt/lists/
    state: directory
    mode: 0755

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes



  